### PR TITLE
Update TransactionalPerBatch.scala

### PR DESCRIPTION
**Pull request by mamdouhweb**
Scoping the action for each offset range

### CODE REVIEW

**Comment by koeninger** [comment]
To be clear, you're just changing indentation?

**Comment by mamdouhweb** [comment]
Oh no, I am adding the {} to surround the osr in the foreach. It's throwing errors for some reasons without those curly's!

**Comment by koeninger** [comment]
What exactly are you using to try to build it, and what error are you getting?

**Comment by mamdouhweb** [comment]
I get a wrong expression on it and cannot resolve object (osr)

**Comment by koeninger** [comment]
What are you using to build?  sbt? intellij?

**Comment by mamdouhweb** [comment]
intellij/maven

**Comment by koeninger** [comment]
I just now as a test imported the sbt project into intellij and compiled without issue.  It sounds like there's something wrong with your ide configuration.

**Pull request closed without merging**
